name: rfmc1
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - pip:
      - certifi==2025.11.12
      - numpy==2.4.0
      - pandas==2.3.3
      - py4j==0.10.9.7
      - pyarrow==22.0.0
      - pyspark==3.5.1
      - pytz==2025.2
      - tzdata==2025.3
      - ucimlrepo==0.0.7
prefix: C:\Users\U1\miniconda3\envs\rfmc1
